	; WRITING BY TAHIR CAN KOZAN
	; AMAÇ ->
	; F > WREG İSE 0XF0
	; F < WREG İSE 0X0F   PORTC YAZIRILIR

	MOVLW 0X00    ; 0X00 WREG DE
	MOVWF TRISC,0 ; ACCESS BANK DAKİ TRISC YE YÜKLENDİ , OUTUT OLDU PORT C

	MOVLW 0X0F    ; 0X0F WREG DE
	MOVWF 0X50,0  ; WREG DEKİ VERİ ACCESS BANK DAKİ 0X50 ADRESİNE YAZILDI

	MOVLW 0X01    ; 0X01 WREG DE
	ADDLW 0X0F    ; 0X01 WREG DEKİ İLE TOPLANIP WREG E YAZILDI

	CPFSGT 0X50,0 ; ACCESS BANK DAKİ 0X50 ADRESİNDEKİ VERİ WREGDEN BÜYÜKSE SONRAKİ SATIR PAS GECİLECEK , F > WREG
	GOTO NEXT	 ; F < WREG İSE BURAYA GELEREK "NEXT" E GİTTİK
	MOVLW 0XF0    ; F > WREG İSE BU SATIRA GELDİK , 0XF0 WREG DE
	MOVWF PORTC,0 ; WREGDE Kİ ACCESS BANKDAKİ PORTC YE YAZILDI
	GOTO FINISH   ; "FINISH" E GİTTİK
NEXT  MOVLW 0X0F    ; 0X0F WREG DE
	MOVWF PORTC,0 ; WREG DEKİ SAYI ACCESS BANKDAKİ PORTC YE YAZILDI
FINISH SLEEP



