	MOVLW 00 ; belleði sifirlar
	MOVWF TRISC,0 ; BANKED BELLEKTEN PORTLARI OUT YAPTIK
LOOP	MOVLW 0xFF
	MOVWF PORTC,0 ; PORTC YE 0.BELLEKTEN (BANKED) ULAÞIP YAZDIM
	MOVLW 0XFF;
	MOVWF PORTC,0
	GOTO LOOP
	SLEEP

