	CLRF TRISC    ; TRISLER OUTPUT MODUNDA

	MOVLW 0X55    ; WORKNING REGISTER'A 0X55 SAYISI ALINDI
	MOVWF PORTC,0 ; ACCESS BANK DAKİ PORTC YE YAZILDI

LOOP	MOVLW 0XFF    ; TOGGLE ISLEMI ICIN 1111 1111 ALINDI WF YE
	XORWF PORTC,1 ; XOR ILE PORTC DEGERLERI TERSLENDI VE TEKRAR PORTA YAZILDI
	GOTO LOOP	 ; SONSUZ DONGU OCON LOOP LABEL'INA GIDILDI
